backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "profile"
    label: "Profile"
    files:
      - file: "data/author.yaml"  # Update this path as per your actual file
        label: "Author Info"
        name: "author"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Bio", name: "bio", widget: "text" }
          - { label: "Email", name: "email", widget: "string" }
